dist: bionic
sudo: required
language: cpp
compiler:
  - gcc
before_install:
  - sudo dpkg --add-architecture i386
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 86B72ED9
  - sudo add-apt-repository 'deb [arch=amd64] https://mirror.mxe.cc/repos/apt bionic main'
  - sudo apt-get -qq update
  - sudo apt-get install -y texlive-binaries texlive-metapost libproj-dev libwxgtk3.0-dev libvtk6-dev survex imagemagick ghostscript libsqlite3-tcl
  - sudo apt-get install -y mxe-i686-w64-mingw32.static-binutils mxe-i686-w64-mingw32.static-bzip2 mxe-i686-w64-mingw32.static-expat mxe-i686-w64-mingw32.static-freetype-bootstrap mxe-i686-w64-mingw32.static-gcc mxe-i686-w64-mingw32.static-gettext mxe-i686-w64-mingw32.static-glib mxe-i686-w64-mingw32.static-harfbuzz mxe-i686-w64-mingw32.static-jpeg mxe-i686-w64-mingw32.static-libiconv mxe-i686-w64-mingw32.static-libpng mxe-i686-w64-mingw32.static-tiff mxe-i686-w64-mingw32.static-vtk mxe-i686-w64-mingw32.static-wxwidgets mxe-i686-w64-mingw32.static-xz mxe-i686-w64-mingw32.static-zlib mxe-i686-w64-mingw32.static-proj
  - sudo apt-get install -y wine
before_script:
  - export PATH=/usr/lib/mxe/usr/bin:$PATH
  - sudo sed -i '/pattern="PDF"/d' /etc/ImageMagick-6/policy.xml
  - wget -qO - https://github.com/therion/therion/archive/master.tar.gz | tar -xz && mv therion-master ../therion
script:
  - pushd ../therion
  - make config-debian
  - make ./therion
  - make samples
  - make library
  - make config-win32cross
  - make
  - popd
  - wine InnoSetup/ISCC.exe therion.iss 
